INSERT INTO requirement (project_id, requirement, description, status, progress, tech_backend, tech_web, tech_mobile) VALUES
(1, 'User Authentication', 'Implement user authentication system', 'In Progress', 50, TRUE, TRUE, FALSE),
(1, 'Database Design', 'Create database schema', 'Completed', 100, TRUE, FALSE, FALSE),
(1, 'RESTful API Development', 'Develop APIs for CRUD operations', 'In Progress', 75, TRUE, TRUE, FALSE),
(1, 'UI Design', 'Design user interface', 'Pending', 25, FALSE, TRUE, TRUE),
(2, 'Payment Gateway Integration', 'Integrate payment gateway', 'In Progress', 60, TRUE, TRUE, FALSE),
(2, 'User Profile Management', 'Implement user profile functionality', 'Completed', 100, TRUE, FALSE, FALSE),
(2, 'Frontend Development', 'Develop frontend components', 'In Progress', 70, FALSE, TRUE, TRUE),
(2, 'Bug Fixes', 'Resolve bugs reported in testing', 'Pending', 40, TRUE, TRUE, TRUE),
(3, 'Database Migration', 'Migrate data to new database system', 'Completed', 100, TRUE, FALSE, FALSE),
(3, 'API Optimization', 'Optimize API performance', 'In Progress', 80, TRUE, FALSE, FALSE),
(3, 'Mobile App Development', 'Develop mobile application', 'Pending', 30, TRUE, FALSE, TRUE),
(4, 'Push Notification Setup', 'Configure push notification service', 'In Progress', 50, TRUE, FALSE, TRUE),
(4, 'Documentation', 'Document system architecture', 'Completed', 100, TRUE, TRUE, FALSE),
(4, 'Security Enhancements', 'Implement security measures', 'In Progress', 90, TRUE, FALSE, FALSE),
(5, 'Analytics Integration', 'Integrate analytics platform', 'Pending', 20, TRUE, TRUE, FALSE),
(5, 'Performance Testing', 'Conduct performance testing', 'In Progress', 65, TRUE, FALSE, FALSE),
(5, 'Deployment', 'Deploy application to production server', 'Completed', 100, TRUE, TRUE, TRUE),
(6, 'Feature Implementation', 'Implement new features', 'In Progress', 85, TRUE, TRUE, TRUE),
(6, 'Code Review', 'Perform code review for quality assurance', 'Pending', 45, TRUE, TRUE, FALSE),
(6, 'Client Feedback', 'Incorporate client feedback', 'Completed', 100, TRUE, FALSE, FALSE),
(7, 'Server Configuration', 'Configure server settings', 'In Progress', 55, TRUE, FALSE, FALSE),
(7, 'User Documentation', 'Create user documentation', 'Completed', 100, TRUE, TRUE, FALSE),
(7, 'Beta Testing', 'Conduct beta testing with select users', 'Pending', 35, TRUE, TRUE, TRUE),
(8, 'Database Optimization', 'Optimize database performance', 'In Progress', 75, TRUE, FALSE, FALSE),
(8, 'Error Handling', 'Implement error handling mechanisms', 'Completed', 100, TRUE, TRUE, FALSE),
(8, 'Third-Party Integration', 'Integrate third-party services', 'Pending', 25, TRUE, TRUE, FALSE),
(9, 'Scalability Planning', 'Plan for system scalability', 'In Progress', 80, TRUE, FALSE, FALSE),
(9, 'Accessibility Improvements', 'Improve accessibility features', 'Completed', 100, TRUE, TRUE, FALSE),
(9, 'Mobile Responsiveness', 'Optimize for mobile devices', 'Pending', 30, TRUE, TRUE, TRUE),
(10, 'Backup and Recovery Setup', 'Implement backup and recovery solution', 'In Progress', 60, TRUE, FALSE, FALSE),
(10, 'Localization', 'Add support for multiple languages', 'Completed', 100, TRUE, TRUE, FALSE),
(10, 'Performance Monitoring', 'Set up performance monitoring tools', 'Pending', 40, TRUE, FALSE, FALSE),
(11, 'Feature Testing', 'Test new features for functionality', 'In Progress', 85, TRUE, FALSE, FALSE),
(11, 'User Training', 'Provide training for end users', 'Completed', 100, TRUE, TRUE, FALSE),
(11, 'Stakeholder Meetings', 'Hold meetings with project stakeholders', 'Pending', 55, TRUE, FALSE, FALSE),
(12, 'Data Backup', 'Regularly backup application data', 'In Progress', 70, TRUE, FALSE, FALSE),
(12, 'Performance Tuning', 'Optimize system performance', 'Completed', 100, TRUE, TRUE, FALSE),
(12, 'Mobile App Updates', 'Release updates for mobile app', 'Pending', 45, TRUE, FALSE, TRUE),
(13, 'Database Maintenance', 'Perform routine database maintenance', 'In Progress', 75, TRUE, FALSE, FALSE),
(13, 'Feature Prioritization', 'Prioritize features for development', 'Completed', 100, TRUE, TRUE, FALSE),
(13, 'UI/UX Enhancements', 'Enhance user interface and experience', 'Pending', 60, TRUE, TRUE, TRUE),
(14, 'Server Upgrades', 'Upgrade server hardware and software', 'In Progress', 80, TRUE, FALSE, FALSE),
(14, 'Code Optimization', 'Optimize code for efficiency', 'Completed', 100, TRUE, TRUE, FALSE),
(14, 'User Feedback Analysis', 'Analyze user feedback for improvements', 'Pending', 65, TRUE, FALSE, FALSE),
(15, 'Security Auditing', 'Conduct security audits', 'In Progress', 85, TRUE, FALSE, FALSE),
(15, 'Documentation Updates', 'Update system documentation', 'Completed', 100, TRUE, TRUE, FALSE),
(15, 'User Acceptance Testing', 'Perform user acceptance testing', 'Pending', 70, TRUE, FALSE, FALSE),
(16, 'API Versioning', 'Implement versioning for APIs', 'In Progress', 90, TRUE, FALSE, FALSE),
(16, 'Feature Requests', 'Process and prioritize feature requests', 'Completed', 100, TRUE, TRUE, FALSE),
(16, 'User Support', 'Provide support for end users', 'Pending', 75, TRUE, FALSE, FALSE),
(17, 'Database Backup Automation', 'Automate database backup processes', 'In Progress', 95, TRUE, FALSE, FALSE),
(17, 'Code Reviews', 'Conduct regular code reviews', 'Completed', 100, TRUE, TRUE, FALSE),
(17, 'Integration Testing', 'Perform integration testing', 'Pending', 80, TRUE, FALSE, FALSE),
(18, 'Server Maintenance', 'Perform routine server maintenance', 'In Progress', 100, TRUE, FALSE, FALSE),
(18, 'Feature Demos', 'Prepare demos for new features', 'Completed', 100, TRUE, TRUE, FALSE),
(18, 'Performance Reviews', 'Conduct performance reviews', 'Pending', 85, TRUE, FALSE, FALSE),
(19, 'Data Encryption', 'Implement data encryption measures', 'In Progress', 100, TRUE, FALSE, FALSE),
(19, 'Code Refactoring', 'Refactor code for better maintainability', 'Completed', 100, TRUE, TRUE, FALSE),
(19, 'User Surveys', 'Collect feedback through user surveys', 'Pending', 90, TRUE, FALSE, FALSE),
(20, 'Continuous Integration', 'Set up continuous integration pipeline', 'In Progress', 100, TRUE, FALSE, FALSE),
(20, 'Code Documentation', 'Document code for future reference', 'Completed', 100, TRUE, TRUE, FALSE),
(20, 'User Permissions Management', 'Manage user permissions and roles', 'Pending', 95, TRUE, FALSE, FALSE);
-- Repeat for additional data points
  
