INSERT INTO requirement (project_id, requirement, description, status, progress, tech_backend, tech_web, tech_mobile) VALUES
(1, 'User Authentication', 'Implement user authentication system', 'In Progress', 50, TRUE, TRUE, FALSE),
(1, 'Database Design', 'Create database schema', 'Completed', 100, TRUE, FALSE, FALSE),
(2, 'Payment Gateway Integration', 'Integrate payment gateway', 'In Progress', 60, TRUE, TRUE, FALSE),
(2, 'User Profile Management', 'Implement user profile functionality', 'Completed', 100, TRUE, FALSE, FALSE),
(3, 'Database Migration', 'Migrate data to new database system', 'Completed', 100, TRUE, FALSE, FALSE),
(3, 'API Optimization', 'Optimize API performance', 'In Progress', 80, TRUE, FALSE, FALSE),
(4, 'Push Notification Setup', 'Configure push notification service', 'In Progress', 50, TRUE, FALSE, TRUE),
(4, 'Documentation', 'Document system architecture', 'Completed', 100, TRUE, TRUE, FALSE),
(5, 'Analytics Integration', 'Integrate analytics platform', 'Pending', 20, TRUE, TRUE, FALSE),
(5, 'Performance Testing', 'Conduct performance testing', 'In Progress', 65, TRUE, FALSE, FALSE),
(6, 'Feature Implementation', 'Implement new features', 'In Progress', 85, TRUE, TRUE, TRUE),
(6, 'Code Review', 'Perform code review for quality assurance', 'Pending', 45, TRUE, TRUE, FALSE),
(7, 'Server Configuration', 'Configure server settings', 'In Progress', 55, TRUE, FALSE, FALSE),
(7, 'User Documentation', 'Create user documentation', 'Completed', 100, TRUE, TRUE, FALSE),
(8, 'Database Optimization', 'Optimize database performance', 'In Progress', 75, TRUE, FALSE, FALSE),
(8, 'Error Handling', 'Implement error handling mechanisms', 'Completed', 100, TRUE, TRUE, FALSE),
(9, 'Scalability Planning', 'Plan for system scalability', 'In Progress', 80, TRUE, FALSE, FALSE),
(9, 'Accessibility Improvements', 'Improve accessibility features', 'Completed', 100, TRUE, TRUE, FALSE),
(10, 'Backup and Recovery Setup', 'Implement backup and recovery solution', 'In Progress', 60, TRUE, FALSE, FALSE),
(10, 'Localization', 'Add support for multiple languages', 'Completed', 100, TRUE, TRUE, FALSE),
(11, 'Feature Testing', 'Test new features for functionality', 'In Progress', 85, TRUE, FALSE, FALSE),
(11, 'User Training', 'Provide training for end users', 'Completed', 100, TRUE, TRUE, FALSE),
(12, 'Data Backup', 'Regularly backup application data', 'In Progress', 70, TRUE, FALSE, FALSE),
(12, 'Performance Tuning', 'Optimize system performance', 'Completed', 100, TRUE, TRUE, FALSE),
(13, 'Database Maintenance', 'Perform routine database maintenance', 'In Progress', 75, TRUE, FALSE, FALSE),
(13, 'Feature Prioritization', 'Prioritize features for development', 'Completed', 100, TRUE, TRUE, FALSE),
(14, 'Server Upgrades', 'Upgrade server hardware and software', 'In Progress', 80, TRUE, FALSE, FALSE),
(14, 'Code Optimization', 'Optimize code for efficiency', 'Completed', 100, TRUE, TRUE, FALSE),
(15, 'Security Auditing', 'Conduct security audits', 'In Progress', 85, TRUE, FALSE, FALSE),
(15, 'Documentation Updates', 'Update system documentation', 'Completed', 100, TRUE, TRUE, FALSE),
(16, 'API Versioning', 'Implement versioning for APIs', 'In Progress', 90, TRUE, FALSE, FALSE),
(16, 'Feature Requests', 'Process and prioritize feature requests', 'Completed', 100, TRUE, TRUE, FALSE),
(17, 'Database Backup Automation', 'Automate database backup processes', 'In Progress', 95, TRUE, FALSE, FALSE),
(17, 'Code Reviews', 'Conduct regular code reviews', 'Completed', 100, TRUE, TRUE, FALSE),
(18, 'Server Maintenance', 'Perform routine server maintenance', 'In Progress', 100, TRUE, FALSE, FALSE),
(18, 'Feature Demos', 'Prepare demos for new features', 'Completed', 100, TRUE, TRUE, FALSE),
(19, 'Data Encryption', 'Implement data encryption measures', 'In Progress', 100, TRUE, FALSE, FALSE),
(19, 'Code Refactoring', 'Refactor code for better maintainability', 'Completed', 100, TRUE, TRUE, FALSE),
(20, 'Continuous Integration', 'Set up continuous integration pipeline', 'In Progress', 100, TRUE, FALSE, FALSE),
(20, 'Code Documentation', 'Document code for future reference', 'Completed', 100, TRUE, TRUE, FALSE),
(21, 'Feature Prioritization', 'Prioritize features for development', 'In Progress', 90, TRUE, TRUE, FALSE),
(21, 'User Feedback Analysis', 'Analyze user feedback for improvements', 'Completed', 100, TRUE, TRUE, FALSE),
(22, 'Database Migration', 'Migrate data to new database system', 'Pending', 80, TRUE, FALSE, FALSE),
(22, 'Security Enhancements', 'Implement security measures', 'In Progress', 95, TRUE, FALSE, FALSE),
(23, 'UI/UX Design', 'Design user interface for mobile app', 'Completed', 100, TRUE, TRUE, TRUE),
(23, 'API Development', 'Develop APIs for mobile app backend', 'In Progress', 75, TRUE, FALSE, TRUE),
(24, 'Documentation', 'Document system architecture', 'Completed', 100, TRUE, TRUE, FALSE),
(24, 'Testing', 'Conduct comprehensive testing', 'In Progress', 80, TRUE, TRUE, FALSE),
(25, 'Feature Development', 'Develop new features', 'Completed', 100, TRUE, TRUE, TRUE),
(25, 'Bug Fixes', 'Address reported bugs', 'In Progress', 90, TRUE, TRUE, TRUE),
(26, 'Performance Optimization', 'Optimize application performance', 'Completed', 100, TRUE, TRUE, FALSE),
(26, 'Database Maintenance', 'Perform routine database maintenance', 'In Progress', 95, TRUE, FALSE, FALSE),
(27, 'User Authentication', 'Implement secure user authentication', 'Completed', 100, TRUE, TRUE, FALSE),
(27, 'Data Validation', 'Implement data validation mechanisms', 'In Progress', 100, TRUE, FALSE, FALSE),
(28, 'UI/UX Enhancements', 'Improve user interface design', 'Completed', 100, TRUE, TRUE, FALSE),
(28, 'Backend Development', 'Develop backend functionality', 'In Progress', 90, TRUE, FALSE, FALSE),
(29, 'Payment Integration', 'Integrate payment gateway', 'Completed', 100, TRUE, TRUE, FALSE),
(29, 'Feature Implementation', 'Implement new features', 'In Progress', 80, TRUE, TRUE, TRUE),
(30, 'API Documentation', 'Create comprehensive API documentation', 'Completed', 100, TRUE, TRUE, FALSE),
(30, 'Performance Testing', 'Conduct performance testing', 'In Progress', 95, TRUE, FALSE, FALSE),
(31, 'Database Optimization', 'Optimize database performance', 'Completed', 100, TRUE, TRUE, FALSE),
(31, 'User Interface Design', 'Design user interface for web application', 'In Progress', 100, TRUE, TRUE, FALSE),
(32, 'Backend Development', 'Develop backend functionality', 'Completed', 100, TRUE, FALSE, FALSE),
(32, 'User Authentication', 'Implement user authentication system', 'In Progress', 90, TRUE, TRUE, FALSE),
(33, 'Mobile App Development', 'Develop mobile application', 'Completed', 100, TRUE, FALSE, TRUE),
(33, 'Push Notification Integration', 'Integrate push notification service', 'In Progress', 100, TRUE, FALSE, TRUE),
(34, 'Database Migration', 'Migrate data to new database system', 'Completed', 100, TRUE, FALSE, FALSE),
(34, 'API Optimization', 'Optimize API performance', 'In Progress', 95, TRUE, FALSE, FALSE),
(35, 'Documentation', 'Document system architecture', 'Completed', 100, TRUE, TRUE, FALSE),
(35, 'Testing', 'Conduct comprehensive testing', 'In Progress', 100, TRUE, TRUE, FALSE),
(36, 'Feature Development', 'Develop new features', 'Completed', 100, TRUE, TRUE, TRUE),
(36, 'Bug Fixes', 'Address reported bugs', 'In Progress', 90, TRUE, TRUE, TRUE),
(37, 'Performance Optimization', 'Optimize application performance', 'Completed', 100, TRUE, TRUE, FALSE),
(37, 'Database Maintenance', 'Perform routine database maintenance', 'In Progress', 95, TRUE, FALSE, FALSE),
(38, 'User Authentication', 'Implement secure user authentication', 'Completed', 100, TRUE, TRUE, FALSE),
(38, 'Data Validation', 'Implement data validation mechanisms', 'In Progress', 100, TRUE, FALSE, FALSE),
(39, 'UI/UX Enhancements', 'Improve user interface design', 'Completed', 100, TRUE, TRUE, FALSE),
(39, 'Backend Development', 'Develop backend functionality', 'In Progress', 90, TRUE, FALSE, FALSE),
(40, 'Payment Integration', 'Integrate payment gateway', 'Completed', 100, TRUE, TRUE, FALSE),
(40, 'Feature Implementation', 'Implement new features', 'In Progress', 80, TRUE, TRUE, TRUE);
-- Repeat for additional data points
